version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4-stretch-browsers
    steps:
      - checkout
      - run: echo "Start build"
      - run: yarn install
      - run: yarn build
      - run: ls -la dist/      
  deploy:
    docker:
      - image: temandodx/doc-platform
    environment:
      - AWS_S3_BUCKET_NAME: labo.tuemu.com
    steps:
      - run:
          name: Deploy to S3 if branch is Master.
          command:
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              aws s3 sync ~/repo/site s3://${AWS_S3_BUCKET_NAME}/ --exact-timestamps --delete --acl public-read
            fi        
  lint:
    docker:
      - image: circleci/node:8.9.4-stretch-browsers
    steps:
      - checkout
      - run: echo "Start lint"
      - run: yarn install
      - run: yarn lint
  test:
    docker:
      - image: circleci/node:8.9.4-stretch-browsers
    steps:
      - checkout
      - run: echo "Start test"
      - run: yarn install
      - run: yarn test
  e2e:
    docker:
      - image: circleci/node:8.9.4-stretch-browsers
    steps:
      - checkout
      - run: echo "Start e2e"
      - run: yarn install
      - run: yarn e2e
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy
